---
version: "3.5"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ./config:/config
      - ./media/tv:/tv
      - ./media/movies:/movies
      - ./media/kidmovies:/kidmovies
      - ./media/private:/private
    restart: unless-stopped
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
  rutorrent:
    image: linuxserver/rutorrent
    #build:
      #context: .
      #dockerfile: Dockerfile-rutorrent
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./media:/media
    ports:
      - 32500:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
  telegram:
    container_name: telegram
    build:
      context: telegram
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "24"
    volumes:
    - "./telegram:/var/www/telegram"
    - "./downloads:/downloads"
    restart: unless-stopped

